#Содержит пароли в чистом виде, но в base64 кодировке (Kubernetes требует это для секретов).
#Обычно пароли не хранят в открытом виде, поэтому мы их хешируем для конфига ClickHouse,
# а в секрете храним для того, чтобы можно было передать в под как переменные окружения 
#(если нужно) или для того, чтобы администратор знал пароли.

apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: clickhouse
type: Opaque
data:
  # Пароли в base64 (генерируются автоматически)
  admin-password: {{ .Values.users.admin.password | b64enc }}
  app-user-password: {{ .Values.users.app_user.password | b64enc }}
  readonly-user-password: {{ .Values.users.readonly_user.password | b64enc }}